# Generated by Django 4.2 on 2023-05-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hashtag",
            name="name",
            field=models.CharField(
                blank=True, default=None, max_length=255, unique=True
            ),
        ),
    ]
