# Generated by Django 4.2 on 2023-05-03 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_add_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="relationship",
            options={"ordering": ("-created_at",)},
        ),
    ]
