# Generated by Django 4.2 on 2023-05-03 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("-comment_date",)},
        ),
    ]
